##replace the lines with the "$"
services:
  app:
    image: idkspanish/dbdemo:latest
    container_name: app
    ports:
      - "5000:8080"
    depends_on:
        - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/${DBName}
      - DB_USER=${DBUser}
      - DB_PASS=${DBPass}

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=${DBUser}
      - POSTGRES_PASSWORD=${DBPass}
      - POSTGRES_DB=${DBName}
    ports:
      - "5433:5432"
